### ISSUE TITLE
Hover descriptions in experimental design

### ISSUE THREAD

**Issue by dangeles** [WormLabCaltech/alaska#19]
The 1-factor description currently reads:

A 1-factor design contrasts a control sample with a single experimental sample.

However, I'm hearing from beta users this is confusing, and I agree. We should modify this to read:

A 1-factor design finds the differentially expressed transcripts between an experimentally perturbed sample (for example, a mutant strain) and a reference sample (often the wild-type strain). This is the most common experimental design for RNA-seq.

**Comment by Lioscro** [comment]
Done in commit [5436bb571e1ced35a8441743f376cda0ce28d404](https://github.com/WormLabCaltech/alaska/commit/5436bb571e1ced35a8441743f376cda0ce28d404).
