### ISSUE TITLE
Organism field in metadata

### ISSUE THREAD

**Issue by dangeles** [WormLabCaltech/alaska#23]
Currently the organism metadata field just says organism. In fact, this should be two fields:

Organism Species: Dropdown menu of scientific names of species
Species Genome: Dropdown menu of the genome versions, ordered in reverse numeric order. I.e., latest genome version first.

**Comment by Lioscro** [comment]
Implemented in [ff567b0d5596b3822075bcfeb5091003c2d075b5](https://github.com/WormLabCaltech/alaska/commit/ff567b0d5596b3822075bcfeb5091003c2d075b5) and [5c1df7ea223cbdc857f629b1ab81670c1f061235](https://github.com/WormLabCaltech/alaska/commit/5c1df7ea223cbdc857f629b1ab81670c1f061235).
